---
extends: default

ignore: |
  .ansible/

rules:
  line-length:
    max: 120
  truthy:
    allowed-values: ["true", "false"]
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
